version: '3.3'
services:
  mysql:
    image: mysql:8.0
    container_name: "mysql-container"
    restart: always
    environment:
      MYSQL_DATABASE: 'SkyloovAdminDB'
      MYSQL_USER: 'superadmin'
      MYSQL_PASSWORD: 'loovskypswd'
      MYSQL_ROOT_PASSWORD: 'superLoov'
    ports:
      - '3306:3306'
    volumes:
      - db-mysql:/var/lib/mysql
volumes:
  db-mysql:



