# Generated by Django 3.2.19 on 2023-06-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
